src/Entity/Filmes.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FilmesRepository")
 */
class Filmes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo;

    /**
     * @ORM\Column(type="text")
     */
    private $descricao;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $ano_lancamento;

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getTitulo()
    {
        return $this->titulo;
    }

    /**
     * @param mixed $titulo
     * @return Filmes
     */
    public function setTitulo($titulo)
    {
        $this->titulo = $titulo;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getDescricao()
    {
        return $this->descricao;
    }

    /**
     * @param mixed $descricao
     * @return Filmes
     */
    public function setDescricao($descricao)
    {
        $this->descricao = $descricao;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAnoLancamento()
    {
        return $this->ano_lancamento;
    }

    /**
     * @param mixed $ano_lancamento
     * @return Filmes
     */
    public function setAnoLancamento($ano_lancamento)
    {
        $this->ano_lancamento = $ano_lancamento;
        return $this;
    }
}

src/Form/FilmesType.php
<?php

namespace App\Form;

use App\Entity\Filmes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titulo')
            ->add('descricao')
            ->add('ano_lancamento')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Filmes::class,
        ]);
    }
}

src/Controller/FilmesController.php
<?php

namespace App\Controller;

use App\Entity\Filmes;
use App\Form\FilmesType;
use App\Repository\FilmesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Knp\Component\Pager\Paginator;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/filmes")
 */
class FilmesController extends Controller
{
    /**
     * @Route("/", name="filmes_index", methods="GET")
     */
    public function index(FilmesRepository $filmesRepository, Request $request): Response
    {
        $paginator = $this->get("knp_paginator");
        $filmes = $filmesRepository->findAll();
        $filmes = $paginator->paginate($filmes, $request->query->getInt('page', 1), 8);

        return $this->render('filmes/index.html.twig', ['filmes' => $filmes]);
    }

    /**
     * @Route("/new", name="filmes_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $filme = new Filmes();
        $form = $this->createForm(FilmesType::class, $filme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($filme);
            $em->flush();

            return $this->redirectToRoute('filmes_index');
        }

        return $this->render('filmes/new.html.twig', [
            'filme' => $filme,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="filmes_show", methods="GET")
     */
    public function show(Filmes $filme): Response
    {
        return $this->render('filmes/show.html.twig', ['filme' => $filme]);
    }

    /**
     * @Route("/{id}/edit", name="filmes_edit", methods="GET|POST")
     */
    public function edit(Request $request, Filmes $filme): Response
    {
        $form = $this->createForm(FilmesType::class, $filme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('filmes_edit', ['id' => $filme->getId()]);
        }

        return $this->render('filmes/edit.html.twig', [
            'filme' => $filme,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="filmes_delete", methods="DELETE")
     */
    public function delete(Request $request, Filmes $filme): Response
    {
        if ($this->isCsrfTokenValid('delete'.$filme->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($filme);
            $em->flush();
        }

        return $this->redirectToRoute('filmes_index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}{% endblock %}
</head>
<body>
<div class="container mt-5">
    {% block body %}{% endblock %}
</div>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/filmes/_delete_form.html.twig
<form method="post" action="{{ path('filmes_delete', {'id': filme.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ filme.id) }}">
    <button class="btn">Delete</button>
</form>

templates/filmes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/filmes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Filmes{% endblock %}

{% block body %}
    <h1>Edit Filmes</h1>

    {{ include('filmes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('filmes_index') }}">back to list</a>

    {{ include('filmes/_delete_form.html.twig') }}
{% endblock %}

templates/filmes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Filmes index{% endblock %}

{% block body %}
    <a href="{{ path('filmes_new') }}" class="btn btn-primary float-right">Novo Filme</a>
    <h1>Filmes index</h1>

    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>{{ knp_pagination_sortable(filmes, 'Id', 'id') }}</th>
                <th>{{ knp_pagination_sortable(filmes, 'Titulo', 'titulo') }}</th>
                <th>{{ knp_pagination_sortable(filmes, 'Descrição', 'descricao') }}</th>
                <th>{{ knp_pagination_sortable(filmes, 'Lançamento', 'ano_lancamento') }}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for filme in filmes %}
            <tr>
                <td>{{ filme.id }}</td>
                <td>{{ filme.titulo }}</td>
                <td>{{ filme.descricao }}</td>
                <td>{{ filme.anoLancamento }}</td>
                <td>
                    <a href="{{ path('filmes_show', {'id': filme.id}) }}">show</a>
                    <a href="{{ path('filmes_edit', {'id': filme.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr>
    {{ knp_pagination_render(filmes) }}

    <a href="{{ path('filmes_new') }}">Create new</a>
{% endblock %}

templates/filmes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Filmes{% endblock %}

{% block body %}
    <h1>Create new Filmes</h1>

    {{ include('filmes/_form.html.twig') }}

    <a href="{{ path('filmes_index') }}">back to list</a>
{% endblock %}

templates/filmes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Filmes{% endblock %}

{% block body %}
    <h1>Filmes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ filme.id }}</td>
            </tr>
            <tr>
                <th>Titulo</th>
                <td>{{ filme.titulo }}</td>
            </tr>
            <tr>
                <th>Descricao</th>
                <td>{{ filme.descricao }}</td>
            </tr>
            <tr>
                <th>Ano_lancamento</th>
                <td>{{ filme.anoLancamento }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('filmes_index') }}">back to list</a>

    <a href="{{ path('filmes_edit', {'id': filme.id}) }}">edit</a>

    {{ include('filmes/_delete_form.html.twig') }}
{% endblock %}